'use strict';
const kind=new URLSearchParams(location.search).get('game'),board=document.querySelector('#board'),start=document.querySelector('#start'),score=document.querySelector('#score'),message=document.querySelector('#message');
if(kind==='snake'){
 document.querySelector('#name').textContent='SIGNAL SNAKE';document.querySelector('#directions').hidden=false;
 const canvas=document.createElement('canvas');canvas.width=320;canvas.height=320;canvas.setAttribute('aria-label','Snake playfield. Use arrow keys or direction buttons.');board.append(canvas);const ctx=canvas.getContext('2d');let snake,food,dir,next,timer,points,running=false;
 function place(){do{food={x:Math.floor(Math.random()*16),y:Math.floor(Math.random()*16)};}while(snake.some(s=>s.x===food.x&&s.y===food.y));}
 function draw(){ctx.fillStyle='#17221c';ctx.fillRect(0,0,320,320);ctx.strokeStyle='#243325';for(let i=0;i<16;i++){ctx.beginPath();ctx.moveTo(i*20,0);ctx.lineTo(i*20,320);ctx.moveTo(0,i*20);ctx.lineTo(320,i*20);ctx.stroke();}snake.forEach((s,i)=>{ctx.fillStyle=i?'#a4c65e':'#e6ffa3';ctx.fillRect(s.x*20+2,s.y*20+2,16,16);});ctx.fillStyle='#e6a467';ctx.fillRect(food.x*20+4,food.y*20+4,12,12);}
 function reset(){clearInterval(timer);snake=[{x:7,y:8},{x:6,y:8},{x:5,y:8}];dir={x:1,y:0};next=dir;points=0;place();draw();score.textContent='SCORE 0';}
 function end(text){running=false;clearInterval(timer);message.textContent=text;start.textContent='Play again';}
 function tick(){dir=next;const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};const eat=h.x===food.x&&h.y===food.y;const body=eat?snake:snake.slice(0,-1);if(h.x<0||h.x>15||h.y<0||h.y>15||body.some(s=>s.x===h.x&&s.y===h.y))return end('Trail ended. Score: '+points);snake.unshift(h);if(eat){points++;score.textContent='SCORE '+points;if(snake.length===256){draw();return end('You filled the board!');}place();}else snake.pop();draw();}
 function direction(key){const d={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[key];if(d&&!(d.x===-dir.x&&d.y===-dir.y))next=d;}
 start.onclick=()=>{reset();running=true;message.textContent='Collect the orange signals. Avoid walls and your trail.';start.textContent='Restart';timer=setInterval(tick,150);};
 document.addEventListener('keydown',e=>{const map={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};if(map[e.key]){e.preventDefault();direction(map[e.key]);}});document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>direction(b.dataset.dir));document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)end('Paused. Start a new round when you return.');});reset();message.textContent='Arrow keys, WASD, or the direction pad.';
}else if(kind==='pairs'){
 document.querySelector('#name').textContent='PAIR PLAY';board.className='pairs';let first=null,locked=false,moves=0,matched=0,round=0;const symbols=['◆','●','▲','■','✦','☀','☂','☾'];
 function reset(){round++;first=null;locked=false;moves=0;matched=0;score.textContent='MOVES 0';message.textContent='Find the eight matching pairs.';board.replaceChildren();const deck=[...symbols,...symbols];for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}deck.forEach((value,i)=>{const b=document.createElement('button');b.className='tile';b.textContent='·';b.setAttribute('aria-label','Hidden tile '+(i+1));b.onclick=()=>{if(locked||b===first||b.classList.contains('matched'))return;b.textContent=value;b.setAttribute('aria-label',value);if(!first){first=b;return;}moves++;score.textContent='MOVES '+moves;const old=first;first=null;if(old.textContent===value){old.classList.add('matched');b.classList.add('matched');old.disabled=b.disabled=true;matched++;if(matched===8)message.textContent='All pairs found in '+moves+' moves!';}else{locked=true;const current=round;setTimeout(()=>{if(current!==round)return;old.textContent=b.textContent='·';old.setAttribute('aria-label','Hidden tile');b.setAttribute('aria-label','Hidden tile '+(i+1));locked=false;},750);}};board.append(b);});start.textContent='Shuffle & restart';}start.onclick=reset;reset();
}else if(kind==='reaction'){
 document.querySelector('#name').textContent='REACTION ROOM';const target=document.createElement('button');target.className='target';target.textContent='Ready?';board.append(target);let mode='ready',timer,time;function begin(){clearTimeout(timer);mode='wait';target.textContent='Wait for green…';target.style.background='#48352e';message.textContent='Don’t jump the signal.';timer=setTimeout(()=>{mode='go';time=performance.now();target.textContent='NOW!';target.style.background='#d2ef79';target.style.color='#15200a';},1500+Math.random()*2500);start.textContent='Restart';}target.onclick=()=>{if(mode==='wait'){clearTimeout(timer);mode='done';target.textContent='Too soon';message.textContent='Try again. Wait until the target turns green.';}else if(mode==='go'){const ms=Math.round(performance.now()-time);mode='done';score.textContent=ms+' MS';target.textContent=ms+' ms';message.textContent='Nice. Try another round?';}else{target.style.color='';begin();}};start.onclick=()=>{target.style.color='';begin();};message.textContent='Start, then click or tap the target when it turns green.';
}else{message.textContent='Unknown demo. Return to the library.';start.hidden=true;}
