'use strict';
const game=GAMES.find(g=>g.id===new URLSearchParams(location.search).get('id'));
const stage=document.querySelector('#stage'),state=document.querySelector('#player-state');let timer,frame,controller;
function message(title,body){state.hidden=false;state.replaceChildren();const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=body;state.append(h,p);}
function error(text){clearTimeout(timer);frame?.remove();message('This game couldn’t load.',text);document.querySelector('#player-notice').textContent='Try restarting, or return to the library.';}
function favorite(){const saved=Arcade.read('favorites').includes(game.id);const button=document.querySelector('#favorite');button.textContent=saved?'♥ Favorited':'♡ Favorite';button.setAttribute('aria-pressed',saved);}
async function load(){
 clearTimeout(timer);controller?.abort();controller=new AbortController();frame?.remove();message('Loading game…','');document.querySelector('#player-notice').textContent='';
 try{const url=Arcade.source(game);if(game.type==='external'){message('Open game link','This game opens in a new tab.');const a=document.createElement('a');a.className='button primary';a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Open '+game.title;a.onclick=()=>Arcade.recent(game.id);state.append(a);document.querySelector('#fullscreen').disabled=true;return;}
 if(!['local','iframe'].includes(game.type))throw Error('Unsupported game type');
 timer=setTimeout(()=>error('The source did not respond in time. An external provider may block embedding.'),15000);
 if(game.type==='local'&&location.protocol!=='file:'){const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw Error('The local game file is missing or unavailable ('+response.status+').');if(!response.headers.get('content-type')?.includes('text/html'))throw Error('The source is not an HTML game.');}
 frame=document.createElement('iframe');frame.title=game.title;frame.allow='fullscreen';frame.setAttribute('allowfullscreen','');frame.setAttribute('sandbox','allow-scripts allow-same-origin allow-pointer-lock');frame.referrerPolicy='strict-origin-when-cross-origin';frame.onload=()=>{clearTimeout(timer);state.hidden=true;Arcade.recent(game.id);if(game.type==='iframe')document.querySelector('#player-notice').textContent='Blank player? The provider may block embedding. Use the official source link below.';};frame.onerror=()=>error('Check the game source and embedding permissions.');frame.src=url.href;stage.append(frame);
 if(game.type==='iframe'){const a=document.createElement('a');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Open official game source';document.querySelector('#license').append(' · ',a);}
 }catch(e){if(e.name!=='AbortError')error(e.message);}
}
if(!game){message('Game not found','Choose a game from the library.');document.querySelector('#game-title').textContent='Unknown game';document.querySelectorAll('#favorite,#reload,#fullscreen').forEach(b=>b.disabled=true);}else{document.title=game.title+' — Sidequest';document.querySelector('#game-title').textContent=game.title;document.querySelector('#category').textContent=game.category+(game.demo?' / ORIGINAL DEMO':'');document.querySelector('#controls').textContent=game.controls||'See in-game instructions';document.querySelector('#description').textContent=game.description||'';document.querySelector('#license').textContent=game.license||'';favorite();document.querySelector('#favorite').onclick=()=>{Arcade.favorite(game.id);favorite();};document.querySelector('#reload').onclick=load;load();}
document.querySelector('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(stage.requestFullscreen)await stage.requestFullscreen();else Arcade.toast('Fullscreen is unavailable in this browser.');}catch{Arcade.toast('Fullscreen was blocked by your browser.');}};
document.addEventListener('fullscreenchange',()=>document.querySelector('#fullscreen').textContent=document.fullscreenElement?'⛶ Exit fullscreen':'⛶ Fullscreen');
